"""Typed dataclasses for Natural Language Autoencoder (NLA) results.

NLA explanations pair a natural-language verbalization of an activation
with the autoencoder's reconstruction quality so that downstream consumers
can decide whether to trust the text.

See ``prism/docs/NLA.md`` for the technique itself; this module only defines
the data carriers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np


@dataclass
class NLAExplanation:
    """Single-sample NLA result.

    Attributes:
        text: Natural-language explanation generated by the AV (Activation
            Verbalizer). This is the user-facing description of what the
            target layer was "thinking" at this position.
        reconstruction_fve: Fraction of variance explained by the AR's
            reconstruction of the input activation. Range ``[0.0, 1.0]``
            (negative values are clipped to 0). Anthropic reports 0.6-0.8
            for production NLAs on Claude-family models.
        reconstructed_vector: AR's reconstruction of the input activation,
            same shape as the original. ``None`` when the AR output was
            not requested (e.g. text-only mode).
        metadata: Free-form dict carrying ``model_id``, ``layer_idx``,
            ``d_model``, ``backend``, and any other inference-time fields.
    """

    text: str
    reconstruction_fve: float
    reconstructed_vector: Optional[np.ndarray] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not isinstance(self.text, str):
            raise TypeError(f"NLAExplanation.text must be str, got {type(self.text).__name__}")
        if not isinstance(self.reconstruction_fve, (int, float)):
            raise TypeError(
                "NLAExplanation.reconstruction_fve must be a float, "
                f"got {type(self.reconstruction_fve).__name__}"
            )
        # Clip FVE to the documented [0, 1] range. Negative FVE can occur
        # when the AR does worse than the mean — we surface that as 0.0 so
        # downstream consumers can apply a single threshold without
        # checking for negative numbers.
        if self.reconstruction_fve < 0.0:
            self.reconstruction_fve = 0.0
        elif self.reconstruction_fve > 1.0:
            self.reconstruction_fve = 1.0
        if self.reconstructed_vector is not None and not isinstance(
            self.reconstructed_vector, np.ndarray
        ):
            self.reconstructed_vector = np.asarray(self.reconstructed_vector, dtype=np.float32)


@dataclass
class NLABatchResult:
    """Aggregate over a batch of explanations from a single layer.

    Used by :func:`prism.geometry.scan_model_geometry` when an
    ``nla_explainer`` is attached; the ``nla`` block in the scan result
    carries this information.
    """

    layer_idx: int
    n_samples: int
    explanations: List[NLAExplanation]
    summary: str
    mean_fve: float
    fve_std: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "layer_idx": self.layer_idx,
            "n_samples": self.n_samples,
            "explanations": self.explanations,
            "summary": self.summary,
            "mean_fve": self.mean_fve,
            "fve_std": self.fve_std,
        }
